### ISSUE TITLE
Animation Rigging

### ISSUE THREAD

**Issue by Zeroff** [bitDecayGames/fireport#107]
Rigging up the client side animations to the animation steps passed in on the turn.

**Comment by Kenoshen** [comment]
See: 

https://github.com/bitDecayGames/fireport/blob/master/client/Fireport/Assets/Scripts/Game/GameManagerBehaviour.cs#L75

This line is the entry point for the incoming animations from the server that need to be applied to the various game objects.

Also, see:

https://github.com/bitDecayGames/fireport/blob/master/client/Fireport/Assets/Scripts/AnimationEngine/AnimationEngineBehaviour.cs#L32

For where to engage the animation engine to apply the animations to the game pieces.
