### ISSUE TITLE
Start game design doc

### ISSUE THREAD

**Issue by MondayHopscotch** [bitDecayGames/fireport#25]
- [x] Share link to document with team
- [x] Overview of needed screens
- [x] Game mechanics (and the limited extent thereof)
- [x] Art style overview (high-level rough outline)
- [x] Sound style overview (high-level again)

**Comment by Kenoshen** [comment]
Here is the game design doc:

https://docs.google.com/document/d/1HqD8g8FBVJE_fOqGnF1mXw06uLUlTITW13doYgSrBus/edit

**Comment by Zeroff** [comment]
![firstdraftfirstfewscreens](https://user-images.githubusercontent.com/15240322/47400301-d8f5fa80-d6f9-11e8-9dd7-77e257f72628.JPG)
