### ISSUE TITLE
Deal player cards on turn start/end

### ISSUE THREAD

**Issue by MondayHopscotch** [bitDecayGames/fireport#35]
At the start of a game, deal cards to each player (deal max hand size to each player)

**Comment by Kenoshen** [comment]
Whoops, did not mean to close this >.<

**Comment by Zeroff** [comment]
Would this include generating and populating a full game state when the game starts?

**Comment by Kenoshen** [comment]
Whoops, meant to create a PR for this, but this was fixed with d68db26
