### ISSUE TITLE
Rule violation of 2 players in the same position. 

### ISSUE THREAD

**Issue by Zeroff** [bitDecayGames/fireport#71]

**Comment by Kenoshen** [comment]
http://ec2-34-217-206-186.us-west-2.compute.amazonaws.com:8080/api/v1/game/GAME/turn/Arch Duke Franz Furdinand (500): player 0 and player 15 are occupying the same space 2

**Comment by Kenoshen** [comment]
I probably need a game state and inputs to test this.  Probably just need to play another game and track the game states and inputs.

**Comment by Kenoshen** [comment]
In the process of working on the fix for #65 (PR: #80) I actually experienced this type of state occurring.  My guess is that by fixing #65 (merging #80), we will also solve this bug.

Because of that, I am marking this issue as closed.
