### ISSUE TITLE
Establish an easy way to update Ubuntu server with the latest server code and run it

### ISSUE THREAD

**Issue by Kenoshen** [bitDecayGames/fireport#8]
I'm thinking maybe any time you push a commit to master, we could have some automated process that pulls the latest and deploys the server.

Oh @jacque006 we miss you.

**Comment by jacque006** [comment]
Depending on what the server is and if you need any databases, should be easy to slap into a Docker container and get a CI/CD deploy pipeline setup. 

More than happy to host in my kubernetes cluster as well unless you want to run on your own infrastructure.

**Comment by Kenoshen** [comment]
Successfully got nginx running in front of the main server, also now use a deploy.sh script with ansible to get latest server code up to the server.
